Module7 task1
bsgribtmfu/1593103-big-trip-15 pull request #1
Opened 2021-10-01 18:41 UTC by bsgribtmfu

2021-10-08 08:28 UTC, Shramkoweb requested changes

2021-10-08 08:28 UTC, Shramkoweb commented on src/api.js
> +    return fetch( // вернет промис
Имхо - fetch всегда вернет промис - смысл такого комментария не вижу

2021-10-08 08:28 UTC, Shramkoweb commented on src/api.js
> +  static catchError(err) {
Это академия так вам посоветовала? этот метод?

2021-10-08 08:28 UTC, Shramkoweb commented on src/main.js
> +  addButton.disabled = true;
Любой клик дисейблит эту кнопку? ты потом где-то снаружи ее возвращаещь?

2021-10-08 08:28 UTC, Shramkoweb commented on src/presenter/event.js
> +    // this._replaceFormToCard();
??

2021-10-08 08:28 UTC, Shramkoweb commented on src/presenter/filter.js
> +    replaceElement(this._filterComponent, prevFilterComponent); // надо ли делать replace? данные ведь никак не меняются в фильтрах, а следовательно, что там перерисовывать?
Тут не понял когда делать реплейс? В самом начале? Когда ничего не поменялось в фильтре?

2021-10-08 08:28 UTC, Shramkoweb commented on src/presenter/new-event.js
> +import dayjs from 'dayjs';
Импорт библиотек делают всегда в начале файла. Потом уже твои модули

2021-10-08 08:28 UTC, Shramkoweb commented on src/presenter/new-event.js
> +    }
Может какой-то хелпер сделать. Вроде академия вам раньше показывала его. Ведь этот код может очень часто встречаться

2021-10-08 08:28 UTC, Shramkoweb commented on src/presenter/new-event.js
> +    }
Я про `evt.key === 'Escape' || evt.key === 'Esc'` и потом вызов какого-то колбека

2021-10-08 08:28 UTC, Shramkoweb commented on src/utils/abstract-observer.js
> +  _notify(event, payload) {
```suggestion
  // event - тип обновлений
  // payload - данные
  _notify(event, payload) {
```

2021-10-08 08:28 UTC, Shramkoweb commented on src/utils/date.js
> +const msToTime = (durationTime) => {
Я вижу эта ф-я вернет и дату. Я ьы назвал что-то типа durationToDate.

Она не может быть `msTo` потому что миллисекунды ты вычисляешь вот тут   const milliseconds = Math.floor((durationTime % 1000) / 100);

2021-10-08 08:28 UTC, Shramkoweb commented on src/utils/filter.js
> +const filter = {
Диспетчеризация по объекту 👍

2021-10-08 08:28 UTC, Shramkoweb commented on src/view/new-event.js
> +import flatpickr from 'flatpickr';
Импорт библиотеки в начало

2021-10-08 08:28 UTC, Shramkoweb commented on src/view/new-event.js
> +import '../../node_modules/flatpickr/dist/flatpickr.min.css';
А так точно можно?)
```suggestion
import 'flatpickr/dist/flatpickr.min.css';
```
попробуй

2021-10-08 08:28 UTC, Shramkoweb commented on src/view/statistics.js
> +import { STATS_BAR_HEIGHT } from '../mock/constans.js';
А что делаю константы в моках? Моки это чисто для тестов - константы отдельно

2021-10-08 08:28 UTC, Shramkoweb commented on src/view/trip-info.js
> +  switch(true) { // переделать [ диспетчеризация по обьекту ]
Переделать =)) Но потом

2021-10-08 09:06 UTC, bsgribtmfu commented on src/view/statistics.js
> +import { STATS_BAR_HEIGHT } from '../mock/constans.js';
забыл удалить, но у меня уже почти готова новая отрефакторенная версия этого проекта )

2021-10-08 09:08 UTC, bsgribtmfu commented on src/utils/date.js
> +const msToTime = (durationTime) => {
ок, эту функцию я уже удалил, воспользовался методами от dayjs

2021-10-08 14:28 UTC, Shramkoweb commented on src/view/statistics.js
> +import { STATS_BAR_HEIGHT } from '../mock/constans.js';
ок))

2021-10-12 20:10 UTC, bsgribtmfu commented on src/api.js
> +  static catchError(err) {
да)

2021-10-15 14:11 UTC, Shramkoweb commented on src/utils/common.js
> +const getElementsByType = (type, elements, keyName) => [...elements].find((element) => type === element[`${keyName}`]);
А зачем тебе тут каждый рас при поиске чего-то копировать весь массив?

2021-10-15 15:32 UTC, bsgribtmfu commented on src/utils/common.js
> +const getElementsByType = (type, elements, keyName) => [...elements].find((element) => type === element[`${keyName}`]);
ранее юзал другой метод который "мутировал" исходный обьект, забыл убрать

2021-10-15 20:04 UTC, Shramkoweb approved these changes

2021-10-15 20:04 UTC, merged